### ISSUE TITLE
IDA 7.7 til file works on 9.0 Beta 2

### ISSUE THREAD

**Issue by HumanGamer** [emoose/idaxex#7]
Just a heads up, you can just include the 7.7 x360.til file in the 9.0 release :)

**Comment by emoose** [comment]
Hm, it always gives me an IDA internal error 10245 when I try with it :/

Is your x360.til from the last idaxex release or did you get it from somewhere else?

Maybe some setting from my last IDA version is affecting it, I'll try with a fresh setup soon.

**Comment by HumanGamer** [comment]
Yeah it's from the last idaxex release for 7.7. In fact, if you look, even the one for IDA 7.2 is binary identical.

**Comment by jezza3814** [comment]
this also gives me the internal 10245 error. not sure how you got it to work

**Comment by neverwasd** [comment]
For me, IDA 9.0 crashes when loading x360.til on startup, but if you load it from the Type libraries view (Shift+F11) after loading the executable, it seems to work.

**Comment by neverwasd** [comment]
Unfortunately, it doesn't look like tilib90.zip was archived. Let me know if you find otherwise.

**Comment by emoose** [comment]
Looks like ppc64.dll will call interr(10245) if `getinf_flag(INF_LFLAGS, LFLG_64BIT) == false`, so I guess it's related to the code added to switch hex-rays to 32-bit (not really sure why loading it from type libraries afterward worked fine though, maybe that flag gets reset after the loader is finished?)

Delaying the 32-bit switch to only happen after we've finished loading the XEX seems to let the TIL apply without crashing, but not sure if this could cause other issues (every other loader plugin switches to 32-bit before loading anything...)

If anyone wants to give it a try here's a build: 
[idaxex+xex1tool-0.32_ida90beta.zip](https://github.com/user-attachments/files/16725421/idaxex%2Bxex1tool-0.32_ida90beta.zip)

**Comment by neverwasd** [comment]
Thanks. So far so good, but I've yet to really dig into a project with it at this point.
